name: Publish container image

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
    - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v2
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=edge,branch=main
          type=sha,format=long,prefix=
    - uses: actions/checkout@v3
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        cache-to: type=gha,scope=docker
        cache-from: type=gha,scope=docker,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
